# Generated by Django 4.2.2 on 2023-06-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RenameField(
            model_name='car',
            old_name='created_by',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='created_by',
            new_name='created',
        ),
    ]
